name: Innocent Musings of an Amateur Mind
favicon: null
layout_spectrum: 0.99699
typography_spectrum: 0.24729
title: Innocent Musings of an Amateur Mind
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00fefe'
    - '#000002'
    - '#00295e'
    - '#0067bc'
    - '#169ee0'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
