name: Innocent Musings of an Amateur Mind
favicon: null
layout_spectrum: 0.75511
typography_spectrum: 0.48797
title: Innocent Musings of an Amateur Mind
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00fefe'
    - '#000002'
    - '#00295e'
    - '#0067bc'
    - '#169ee0'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
